### ISSUE TITLE
A progressive Web application with Vue JS, Webpack & Material Design [Part 1]

### ISSUE THREAD

**Issue by madneal** [neal1991/articles-translator#2]
![image](https://cloud.githubusercontent.com/assets/12164075/26136809/b7478288-3af0-11e7-9f2b-cd7b4a1595a0.png)

**Comment by madneal** [comment]
![image](https://cloud.githubusercontent.com/assets/12164075/26137264/b3dbd31c-3af3-11e7-93bb-12822c370704.png)

**Comment by madneal** [comment]
![image](https://cloud.githubusercontent.com/assets/12164075/26159161/64653cbc-3b50-11e7-9ad8-3c187ec6e391.png)

**Comment by Baoyx007** [comment]
校友，哈哈😆
